### ISSUE TITLE
Failing to start dev server

### ISSUE THREAD

**Issue by jim4067** [builderz-labs/builderz-solana-dapp-scaffold#7]
Getting this error when trying to start the dev server.  `nternal error: TypeError: Endpoint URL must start with http: or https:.` full logs below. 

I have `rm -r node_modules package-lock.json` and also switched from npm to yarn but the error persists

full logs 

```bash
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
 ⨯ Internal error: TypeError: Endpoint URL must start with `http:` or `https:`.
    at assertEndpointUrl (./node_modules/@solana/web3.js/lib/index.esm.js:4471:11)
    at new Connection (./node_modules/@solana/web3.js/lib/index.esm.js:6045:25)
    at eval (./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.js:12:77)
    at Object.oN [as useMemo] (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:12:68806)
    at t.useMemo (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:162732)
    at ConnectionProvider (./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.js:12:70)
    at au (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46505)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50067)
    at aj (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at aC (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:52874)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50095)
    at aj (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at aC (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:52874)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50095)
    at ac (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11400)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:14707)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aj (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53793)
    at aC (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:52874)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50095)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42922)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ac (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11400)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:14707)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:45321)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:45321)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:45321)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:45321)
    at a_ (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at aw (/home/jimii/Documents/web3/solana/solana-dapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:45321)
digest: "2342451333"
```

**Comment by 0xNyk** [comment]
Hi, @jim4067 - did you add an .env file and added the RPC url like given in the .env.example file?

 ⨯ Internal error: TypeError: Endpoint URL must start with `http:` or `https:`.

Suggests you didnt add an RPC url.

**Comment by jim4067** [comment]
That was the case. Thanks 👍🏾
